# Code generated by servicegen. DO NOT EDIT.
MODULE_DIR := $(abspath .)
TOOLS_DIR ?= $(abspath ../tools)
BUF := $(TOOLS_DIR)/buf
PROTOC ?= $(TOOLS_DIR)/protoc
DEPENDENCY_DOCKER_TARGETS :=
include dependency-proxy.generated.mk
OAPI_CODEGEN_VERSION := v2.4.1
OAPI_CODEGEN := $(TOOLS_DIR)/oapi-codegen

.PHONY: all gen-proto fmt-proto gen-openapi

all: gen-proto gen-openapi

gen-proto:
	@find . -type f -name 'go.generated.proto.mk' | while read mkfile; do \
		dir=$$(dirname $$mkfile); \
		echo "Generating files in $$dir..."; \
		$(MAKE) -C $$dir -f $$(basename $$mkfile) gen MODULE_DIR="$(MODULE_DIR)" PROTOC="$(PROTOC)"; \
	done

fmt-proto:
	@find . -type f -name '*.proto' | while read protofile; do \
		$(BUF) format -w $$protofile; \
	done

$(OAPI_CODEGEN):
	@mkdir -p $(TOOLS_DIR)
	@echo "Installing oapi-codegen $(OAPI_CODEGEN_VERSION)..."
	@GOBIN=$(TOOLS_DIR) go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@$(OAPI_CODEGEN_VERSION)

gen-openapi: $(OAPI_CODEGEN)
	@find . -type f -name 'go.generated.openapi.mk' | while read mkfile; do \
		dir=$$(dirname $$mkfile); \
		echo "Generating files in $$dir..."; \
		$(MAKE) -C $$dir -f $$(basename $$mkfile) gen MODULE_DIR="$(MODULE_DIR)" OAPI_CODEGEN="$(OAPI_CODEGEN)"; \
	done