# Code generated by servicegen. DO NOT EDIT.
# Make prerequisites need backslash escaping; shell arguments need quotes instead.
make_empty :=
make_space := $(make_empty) $(make_empty)
make_escape_path = $(subst $(make_space),\$(make_space),$(1))
MODULE_DIR := $(abspath .)
TOOLS_DIR ?= $(abspath ../tools)
BUF := $(TOOLS_DIR)/buf
PROTOC ?= $(or $(shell command -v protoc 2>/dev/null),$(TOOLS_DIR)/protoc)
DEPENDENCY_DOCKER_TARGETS :=
include dependency-proxy.generated.mk
OAPI_CODEGEN_VERSION := v2.4.1
OAPI_CODEGEN := $(TOOLS_DIR)/oapi-codegen

.PHONY: all build test gen-proto fmt-proto gen-openapi

all: gen-proto gen-openapi

build: all ## [host] Compile every package in this module
	@go test -run '^$$' ./...

test: all ## [host] Run this module's tests
	@go test ./...

gen-proto:
	@set -e; find . -type f -name 'go.generated.proto.mk' | while IFS= read -r mkfile; do \
		dir=$$(dirname "$$mkfile"); \
		echo "Generating files in $$dir..."; \
		$(MAKE) -C "$$dir" -f "$$(basename "$$mkfile")" gen MODULE_DIR="$(MODULE_DIR)" PROTOC="$(PROTOC)"; \
	done

fmt-proto:
	@set -e; find . -type f -name '*.proto' | while IFS= read -r protofile; do \
		"$(BUF)" format -w "$$protofile"; \
	done

$(call make_escape_path,$(OAPI_CODEGEN)):
	@mkdir -p "$(TOOLS_DIR)"
	@echo "Installing oapi-codegen $(OAPI_CODEGEN_VERSION)..."
	@GOBIN="$(TOOLS_DIR)" go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@$(OAPI_CODEGEN_VERSION)

gen-openapi: $(call make_escape_path,$(OAPI_CODEGEN))
	@set -e; find . -type f -name 'go.generated.openapi.mk' | while IFS= read -r mkfile; do \
		dir=$$(dirname "$$mkfile"); \
		echo "Generating files in $$dir..."; \
		$(MAKE) -C "$$dir" -f "$$(basename "$$mkfile")" gen MODULE_DIR="$(MODULE_DIR)" OAPI_CODEGEN="$(OAPI_CODEGEN)"; \
	done